name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitLab Container Registry
        uses: docker/login-action@v2
        with:
          registry: "registry.gitlab.com"
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

      - name: Build and push API Docker image
        run: |
          cd legacy/apps/api
          docker buildx build --platform linux/amd64,linux/arm64 -t registry.gitlab.com/turbopack:legacy/apps/api .
          docker push registry.gitlab.com/turbopack:legacy/apps/api

      - name: Build and push WebRTC Docker image
        run: |
          cd legacy/apps/webrtc
          docker buildx build --platform linux/amd64,linux/arm64 -t registry.gitlab.com/turbopack:legacy/apps/webrtc .
          docker push registry.gitlab.com/turbopack:legacy/apps/webrtc

      - name: Build and push NodeUtil Docker image
        run: |
          cd legacy/apps/nodeutil
          docker buildx build --platform linux/amd64,linux/arm64 -t registry.gitlab.com/turbopack:legacy/apps/nodeutil .
          docker push registry.gitlab.com/turbopack:legacy/apps/nodeutil

      - name: Build and push WebSocket Docker image
        run: |
          cd legacy/apps/websocket
          docker buildx build --platform linux/amd64,linux/arm64 -t registry.gitlab.com/turbopack:legacy/apps/websocket .
          docker push registry.gitlab.com/turbopack:legacy/apps/websocket

      - name: Build and push Kafka Docker image
        run: |
          cd legacy/apps/kafka
          docker buildx build --platform linux/amd64,linux/arm64 -t registry.gitlab.com/turbopack:legacy/apps/kafka .
          docker push registry.gitlab.com/turbopack:legacy/apps/kafka
